### ISSUE TITLE
Project manager/scrum master: Establish process for managing timeline, scope, budget, and tooling

### ISSUE THREAD

**Issue by krook** [Code-and-Response/Prometeo#55]

**Comment by svaleroc** [comment]
Management system has been established. Interlock with core team: 15 minutes daily call (from monday to friday), biweekly lunch (thurscay) and extraordinary meetings under agreement. Roles and activities have been identified. Next milestone in Februry. Team agreement on personal time to dedicate to Prometeo.

**Comment by krook** [comment]
@svaleroc What time would work well for a regular meeting with the IBM team (which will start to include the Service Corps folks)? Tuesdays 4pm your time? Later?

**Comment by svaleroc** [comment]
@krook Tuesdays 4pm our time, ok for us. Thanks!
