### ISSUE TITLE
Hardware engineer: Decide on casing and attachment mechanism

### ISSUE THREAD

**Issue by krook** [Code-and-Response/Prometeo#6]

**Comment by svaleroc** [comment]
Local 3D printing: 3DSix, Pantur y Addwerk. Under revision to print the first 10 health device units

**Comment by svaleroc** [comment]
Call with IBM Lab Zurich 08/01/2020. Ideas/recommendations from Jonas Weiss (from DeStress team). Interlock with Maria Soimu who is interested in build the prototype for IBM Client Center. We will schedule a meeting with them again in March after Februry testing.
