### ISSUE TITLE
Evaluate the allowed ranges for the 5 toxic gases: Carbon Monoxide, Nitrogen Dioxide, Acrolein, Formaldehyde, Benzene.

### ISSUE THREAD

**Issue by svaleroc** [Code-and-Response/Prometeo#86]
Related to #84. This task focuses on documenting the ranges.

**Comment by krook** [comment]
There is a presentation deck from Marco via Vicenc that has some of these. I'll share in the Box folder.

**Comment by SolSantillan** [comment]
[Notes/Resources on the 5 Toxic Gases](https://ibm.ent.box.com/notes/680279072610)

**Comment by krook** [comment]
I believe this is now done and documented. Can you please confirm @SolSantillan

**Comment by SolSantillan** [comment]
Yes Dan, it is done. I will close it. 
By other side, I asked Joan Herrera to validate with Vicenç, expert nurse in Toxicology, the possible values we are going to consider as green and yellow target.
